[2025-06-15T07:09:02.192+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: retail_analytics_airflowDAG.load manual__2025-06-15T07:04:43.328838+00:00 [queued]>
[2025-06-15T07:09:02.207+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: retail_analytics_airflowDAG.load manual__2025-06-15T07:04:43.328838+00:00 [queued]>
[2025-06-15T07:09:02.208+0000] {taskinstance.py:2170} INFO - Starting attempt 3 of 4
[2025-06-15T07:09:02.230+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load> on 2025-06-15 07:04:43.328838+00:00
[2025-06-15T07:09:02.237+0000] {standard_task_runner.py:60} INFO - Started process 173 to run task
[2025-06-15T07:09:02.241+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'retail_analytics_***DAG', 'load', 'manual__2025-06-15T07:04:43.328838+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline_dag.py', '--cfg-path', '/tmp/tmp_xrgsl4q']
[2025-06-15T07:09:02.244+0000] {standard_task_runner.py:88} INFO - Job 22: Subtask load
[2025-06-15T07:09:02.268+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-15T07:09:02.313+0000] {task_command.py:423} INFO - Running <TaskInstance: retail_analytics_airflowDAG.load manual__2025-06-15T07:04:43.328838+00:00 [running]> on host 7bab5b7171c2
[2025-06-15T07:09:02.409+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='retail_analytics_***DAG' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2025-06-15T07:04:43.328838+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-15T07:04:43.328838+00:00'
[2025-06-15T07:09:02.411+0000] {data_load_to_sql.py:25} INFO - Started loading...
[2025-06-15T07:09:27.704+0000] {logging_mixin.py:188} INFO - ✅ Table 'sales_gold' exists. Data appended.
[2025-06-15T07:09:28.025+0000] {logging_mixin.py:188} INFO - ✅ Table 'customers_gold' exists. Data appended.
[2025-06-15T07:09:28.141+0000] {logging_mixin.py:188} INFO - ✅ Table 'inventory_gold' exists. Data appended.
[2025-06-15T07:09:28.142+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-15T07:09:28.156+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=retail_analytics_***DAG, task_id=load, execution_date=20250615T070443, start_date=20250615T070902, end_date=20250615T070928
[2025-06-15T07:09:28.251+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-15T07:09:28.273+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
